# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"\x0e\n\x0c\x45mptyRequest\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0bNumberReply\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32\x8e\x01\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12-\n\rSayHelloAgain\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12*\n\tSayNumber\x12\r.EmptyRequest\x1a\x0c.NumberReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=20
  _globals['_EMPTYREQUEST']._serialized_end=34
  _globals['_HELLOREQUEST']._serialized_start=36
  _globals['_HELLOREQUEST']._serialized_end=64
  _globals['_HELLOREPLY']._serialized_start=66
  _globals['_HELLOREPLY']._serialized_end=95
  _globals['_NUMBERREPLY']._serialized_start=97
  _globals['_NUMBERREPLY']._serialized_end=126
  _globals['_GREETER']._serialized_start=129
  _globals['_GREETER']._serialized_end=271
# @@protoc_insertion_point(module_scope)
